"
R-modules where R is a multivariate ring such as a polynomial ring or an affine ring.
"
Class {
	#name : #MultivariateModule,
	#superclass : #Module,
	#category : #'Mathematics-Modules-Multivariate'
}

{ #category : #'as yet unclassified' }
MultivariateModule >> basis [
	"Answer a Groebner basis of the receiver according to its monomial ordering."
	^ self notYetImplemented
]

{ #category : #'as yet unclassified' }
MultivariateModule >> leadingModule [
	"Answer the leading module of the receiver according to its monomial ordering."
	^ self notYetImplemented
]

{ #category : #'as yet unclassified' }
MultivariateModule >> ordering [
	"Answer the module monomial ordering of the receiver."
	^ self notYetImplemented
]
