"
PolynomialBenchmark new run

testAdditionOverZ	25.4 per second.
testAdditionOverZ2	283 per second.
testDivisionOverQ	5.23 per second.
testDivisionOverZ	5.25 per second.
testFactorizationOverZ17	10.2 per second
testFiniteField	20.1 per second.
testFiniteFieldPolynomialFactorization	336 per second.
testGCDOverQ	8.2 per second.
testGCDOverZ	4.81 per second.
testGCDOverZ2	10.3 per second.
testMultiplication2OverZ	154 per second.
testMultiplication2OverZ2	681 per second.
testMultiplicationOverZ	2.7 per second.
testMultiplicationOverZ2	4,060 per second.
testMultivariatePolynomialAdditionOverZ	106 per second.
testPseudoDivision	5,060 per second.
testPseudoRemainder	5,050 per second.
testRealRoots	24.4 per second.

testFiniteField	18.2 per second. (25 Dec 2017, after refactoring MultivariatePolynomial and removing MonomialIndexedTuple)
testFiniteFieldPolynomialFactorization	255 per second.
testMultivariatePolynomialAdditionOverZ	102 per second.
testPolynomialAdditionOverZ	33.4 per second.
testPolynomialAdditionOverZ2	269 per second.
testPolynomialDivisionOverQ	3.32 per second.
testPolynomialDivisionOverZ	2.96 per second.
testPolynomialGCDOverQ	3.56 per second.
testPolynomialGCDOverZ	4.74 per second.
testPolynomialGCDOverZ2	24.6 per second.
testPolynomialMultiplication2OverZ	168 per second.
testPolynomialMultiplication2OverZ2	686 per second.
testPolynomialMultiplicationOverZ	2.72 per second.
testPolynomialMultiplicationOverZ2	4,090 per second.
testPolynomialPseudoDivision	4,840 per second.
testPolynomialPseudoRemainder	4,810 per second.
testPolynomialRealRoots	40.7 per second.
testRealAlgebraicNumberAddition	2.9 per second.
testRealAlgebraicNumberDivision	241 per second.
testRealAlgebraicNumberProduct	308 per second.
testRealAlgebraicNumberSquare	5,630 per second.

testFiniteField	17.1 per second.
testFiniteFieldPolynomialFactorization	97.8 per second.
testMultivariatePolynomialAdditionOverZ	93.9 per second.
testPolynomialAdditionOverZ	32.6 per second.
testPolynomialAdditionOverZ2	136 per second.
testPolynomialDivisionOverQ	2.63 per second.
testPolynomialDivisionOverZ	2.74 per second.
testPolynomialGCDOverQ	2.88 per second.
testPolynomialGCDOverZ	4.3 per second.
testPolynomialGCDOverZ2	11.3 per second.
testPolynomialMultiplication2OverZ	163 per second.
testPolynomialMultiplication2OverZ2	628 per second.
testPolynomialMultiplicationOverZ	2.7 per second.
testPolynomialMultiplicationOverZ2	3,760 per second.
testPolynomialPseudoDivision	4,110 per second.
testPolynomialPseudoRemainder	4,080 per second.
testPolynomialRealRoots	39.7 per second.
testRealAlgebraicNumberAddition	5.44 seconds.
testRealAlgebraicNumberDivision	154 per second.
testRealAlgebraicNumberProduct	177 per second.
testRealAlgebraicNumberSquare	4,200 per second.

testFiniteField	17.5 per second. (spur 32 bits)
testFiniteFieldPolynomialFactorization	81.3 per second.
testMultivariatePolynomialAdditionOverZ	86.8 per second.
testPolynomialAdditionOverZ	31.2 per second.
testPolynomialAdditionOverZ2	135 per second.
testPolynomialDivisionOverQ	2.57 per second.
testPolynomialDivisionOverZ	2.64 per second.
testPolynomialGCDOverQ	2.44 per second.
testPolynomialGCDOverZ	3.51 per second.
testPolynomialGCDOverZ2	9.86 per second.
testPolynomialMultiplication2OverZ	105 per second.
testPolynomialMultiplication2OverZ2	627 per second.
testPolynomialMultiplicationOverZ	2.72 per second.
testPolynomialMultiplicationOverZ2	3,400 per second.
testPolynomialPseudoDivision	3,660 per second.
testPolynomialPseudoRemainder	3,640 per second.
testPolynomialRealRoots	38.7 per second.
testRealAlgebraicNumberAddition	5.27 seconds.
testRealAlgebraicNumberDivision	148 per second.
testRealAlgebraicNumberProduct	170 per second.
testRealAlgebraicNumberSquare	3,970 per second.

testFiniteField	14.6 per second.
testFiniteFieldPolynomialFactorization	58.4 per second.
testMultivariatePolynomialAdditionOverZ	51.7 per second.
testPolynomialAdditionOverZ	15.8 per second.
testPolynomialAdditionOverZ2	94 per second.
testPolynomialDivisionOverQ	1.66 per second.
testPolynomialDivisionOverZ	1.67 per second.
testPolynomialGCDOverQ	1.54 per second.
testPolynomialGCDOverZ	2.22 per second.
testPolynomialGCDOverZ2	7.01 per second.
testPolynomialMultiplication2OverZ	78 per second.
testPolynomialMultiplication2OverZ2	384 per second.
testPolynomialMultiplicationOverZ	0.598 per second.
testPolynomialMultiplicationOverZ2	2,220 per second.
testPolynomialPseudoDivision	2,300 per second.
testPolynomialPseudoRemainder	2,300 per second.
testPolynomialRealRoots	27.3 per second.
testRealAlgebraicNumberAddition	5.24 seconds.
testRealAlgebraicNumberDivision	110 per second.
testRealAlgebraicNumberProduct	132 per second.
testRealAlgebraicNumberSquare	2,720 per second.

testFiniteField	11.1 per second.
testFiniteFieldPolynomialFactorization	58 per second.
testMultivariatePolynomialAdditionOverZ	FAILED
testPolynomialAdditionOverZ	11.9 per second.
testPolynomialAdditionOverZ2	76.2 per second.
testPolynomialDivisionOverQ	1.23 per second.
testPolynomialDivisionOverZ	1.12 per second.
testPolynomialGCDOverQ	1.16 per second.
testPolynomialGCDOverZ	1.45 per second.
testPolynomialGCDOverZ2	4.64 per second.
testPolynomialMultiplication2OverZ	33.9 per second.
testPolynomialMultiplication2OverZ2	58.4 per second.
testPolynomialMultiplicationOverZ	0.588 per second.
testPolynomialMultiplicationOverZ2	2,260 per second.
testPolynomialPseudoDivision	1,210 per second.
testPolynomialPseudoRemainder	1,220 per second.
testPolynomialRealRoots	22.8 per second.
testRealAlgebraicNumberAddition	5.28 seconds.
testRealAlgebraicNumberDivision	74.1 per second.
testRealAlgebraicNumberProduct	88.6 per second.
testRealAlgebraicNumberSquare	2,020 per second.

testFiniteField	10.8 per second.
testFiniteFieldPolynomialFactorization	55.1 per second.
testMultivariatePolynomialAdditionOverZ	FAILED
testPolynomialAdditionOverZ	11.9 per second.
testPolynomialAdditionOverZ2	69 per second.
testPolynomialDivisionOverQ	1.2 per second.
testPolynomialDivisionOverZ	1.04 per second.
testPolynomialGCDOverQ	1.12 per second.
testPolynomialGCDOverZ	1.38 per second.
testPolynomialGCDOverZ2	4.25 per second.
testPolynomialMultiplication2OverZ	33 per second.
testPolynomialMultiplication2OverZ2	61.4 per second.
testPolynomialMultiplicationOverZ	0.578 per second.
testPolynomialMultiplicationOverZ2	2,220 per second.
testPolynomialPseudoDivision	1,220 per second.
testPolynomialPseudoRemainder	1,220 per second.
testPolynomialRealRoots	23.1 per second.
testRealAlgebraicNumberAddition	6.11 seconds.
testRealAlgebraicNumberDivision	78.2 per second.
testRealAlgebraicNumberProduct	90.3 per second.
testRealAlgebraicNumberSquare	2,020 per second.

testFiniteField	11.3 per second.
testFiniteFieldPolynomialFactorization	54.5 per second.
testPolynomialAdditionOverZ	10.8 per second.
testPolynomialAdditionOverZ2	75 per second.
testPolynomialDivisionOverQ	1.17 per second.
testPolynomialDivisionOverZ	1.06 per second.
testPolynomialGCDOverQ	1.11 per second.
testPolynomialGCDOverZ	1.38 per second.
testPolynomialGCDOverZ2	4.53 per second.
testPolynomialMultiplication2OverZ	32 per second.
testPolynomialMultiplication2OverZ2	58 per second.
testPolynomialMultiplicationOverZ	0.563 per second.
testPolynomialMultiplicationOverZ2	2,120 per second.
testPolynomialPseudoDivision	1,220 per second.
testPolynomialPseudoRemainder	1,190 per second.
testPolynomialRealRoots	23 per second.
testRealAlgebraicNumberAddition	5.96 seconds.
testRealAlgebraicNumberDivision	70.8 per second.
testRealAlgebraicNumberProduct	81.7 per second.
testRealAlgebraicNumberSquare	1,820 per second
"
Class {
	#name : #PolynomialBenchmark,
	#superclass : #Benchmark,
	#category : #'Mathematics-Tests'
}

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testAdditionOverZ [
	| P f g |
	P := ZZ polynomials.
	f := P atRandomBits: 100 maxDegree: 50.
	g := P atRandomBits: 100 maxDegree: 50.
	10000 timesRepeat: [f + g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testAdditionOverZ2 [
	| P f g |
	P := 'ZZ / 2 :: polynomials'.
	f := P atRandomDegree: 50.
	g := P atRandomDegree: 50.
	10000 timesRepeat: [f + g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testDivisionOverQ [
	| P x f g |
	P := QQ polynomials.
	x := P x.
	'f := x^2 + x + 1 ^ 10.
		g := 1 - x ^ 10'.
	2000 timesRepeat: [f // g. f \\ g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testDivisionOverZ [
	| P x f g |
	P := ZZ polynomials.
	x := P x.
	'f := x^2 + x + 1 ^ 10.
		g := 1 - x ^ 10'.
	2000 timesRepeat: [f // g. f \\ g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testFactorizationOverZ17Degree100 [
	| n f |
	n := 100.
	'f := (ZZ/17) polynomials ! [:x| ((1 to: n) sum: [:i| x^i*i]) + 1]'.
	f factors
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testFactorizationOverZ3Degree11Times20 [
	| F Fx x one f |
	F := ZZ / 3.
	Fx := F polynomials.
	x := Fx x.
	one := Fx one.
	'f := x^11 + (x^9 * 2) + (x^8 * 2) + (x^6) + (x^5) + (x^3 * 2) + (x^2 * 2) + one'.
	20 timesRepeat: [f factors]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testFiniteField [
	"Benchmark Polynomial>>#= and ResidueClass#>>="
	| F |
	F := GaloisField new: 9.
	'((F^3) upTo: 9^3) asSet size = (9^3) ifFalse: [self halt]'
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testGCDOverQ [
	| P x f g |
	P := QQ polynomials.
	x := P x.
'	f := x^4 - 1 ^ 5.
	g := x^6 - 1 ^ 5'.
	2000 timesRepeat: [f gcd: g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testGCDOverZ [
	| P x f g |
	P := ZZ polynomials.
	x := P x.
'	f := x^4 - 1 ^ 5.
	g := x^6 - 1 ^ 5'.
	2000 timesRepeat: [f gcd: g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testGCDOverZ2 [
	| P x f g |
	'P := ZZ / 2 :: polynomials'.
	x := P x.
'	f := x^4 - 1 ^ 5.
	g := x^6 - 1 ^ 5'.
	2000 timesRepeat: [f gcd: g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testMultiplication2OverZ [
	| P f g |
	P := ZZ polynomials.
	f := P atRandomBits: 100 maxDegree: 50.
	g := P atRandomBits: 100 maxDegree: 50.
	100 timesRepeat: [f * g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testMultiplication2OverZ2 [
	| P f g |
	P := 'PrimeField new: 2 :: polynomials'.
	f := P atRandomBits: 100 maxDegree: 50.
	g := P atRandomBits: 100 maxDegree: 50.
	100 timesRepeat: [f * g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testMultiplicationOverZ [
	| P x f |
	P := QQ polynomials.
	x := P x.
	f := x - 1.
	1 to: 9 do: [:i| f := x - i * f * f]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testMultiplicationOverZ2 [
	| P x f |
	P := 'PrimeField new: 2 :: polynomials'.
	x := P x.
	f := x - (1 % 2).
	1 to: 9 do: [:i| f := x - (i % 2) * f * f]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testMultivariatePolynomialAdditionOverZ [
	| P f g |
	P := ZZ polynomialsIn: #(x y z).
	f := P atRandomBits: 100 maxDegree: 50.
	g := P atRandomBits: 100 maxDegree: 50.
	10000 timesRepeat: [f + g]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testPseudoDivision [
	| Zx x a b |
	Zx := ZZ polynomials.
	x := Zx x.
'	a := x^8 + (x^6) - (3*(x^4)) - (3*(x^3)) + (8*(x^2)) + (2*x) - 5.
	b := 3*(x^6) + (5*(x^4)) - (4*(x^2)) - (9*x) + 21'.
	20 timesRepeat: [(a pseudoDivisionBy: b) quotient]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testPseudoRemainder [
	| Zx x a b |
	Zx := ZZ polynomials.
	x := Zx x.
'	a := x^8 + (x^6) - (3*(x^4)) - (3*(x^3)) + (8*(x^2)) + (2*x) - 5.
	b := 3*(x^6) + (5*(x^4)) - (4*(x^2)) - (9*x) + 21'.
	20 timesRepeat: [a pseudoRem: b]
]

{ #category : #'as yet unclassified' }
PolynomialBenchmark >> testRealRoots [
	| x f |
	x := QQ polynomials x.
'	f := (x-(1/2))^2*(x-2)*(x^2 + 1)*(x^2-2)'.
	20 timesRepeat: [f rootsIn: RR]
]
